### PR TITLE
fixes TestGetSubnetsForInstance for #46

### PR DESCRIPTION
**Pull request by polarbizzle**
Mocks the call to GetInterfaces() in subnets_test.go

### CODE REVIEW

**Comment by polarbizzle** [comment]
@theatrus thanks again. Do you think you could cut a release in the near future?

**Comment by theatrus** [comment]
Yes! We'll make a point release this week. Feel free to ping me by Friday or Saturday if that hasn't happened.

**Comment by polarbizzle** [comment]
@theatrus this is the ping for a release if you have some spare cycles.

**Comment by polarbizzle** [comment]
@theatrus could we also get a release that includes these filter by vpc-id changes? This is the only change keeping us on a forked build

**Pull request merged**
